//tealium universal tag - utag.67 ut4.0.202508311047, Copyright 2025 Tealium.com Inc. All Rights Reserved.
var _hjSettings=_hjSettings||{};var hj=hj||function(){(hj.q=hj.q||[]).push(arguments)};try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1,"link":1};u.initialized=false;u.scriptrequested=false;u.queue=[];u.map={"hotjarId":"hjid","hotjarEventConfig":"eventConfig"};u.extend=[function(a,b){try{if(1){const expString=b.hubbleExperiments?Object.values(b.hubbleExperiments)
.map(exp=>exp.name+':'+exp.variant+':'+exp.participantStatus)
.join('|'):'';var userId=b.loginId||null;var siteCountry=b.tiq_siteCountry||null;var siteLanguage=b.siteLanguage||null;var isLoggedIn=b.isLoggedIn;var referrer=b['dom.referrer']||null;var seekPassVerifiedTotal=b.tiq_userProfile['seekPassVerifiedTotal']||null;var latestNonLinkedOutJobApplicationDate=b.tiq_userProfile['latestNonLinkedOutJobApplicationDate']?new Date(b.tiq_userProfile['latestNonLinkedOutJobApplicationDate']).toISOString():null;var experiments=expString||null;window.hj('identify',userId,{site_country:siteCountry,site_language:siteLanguage,login_status:isLoggedIn,referrer:referrer,experiments:experiments,seekpass_verified_total:seekPassVerifiedTotal,latest_job_application_date:latestNonLinkedOutJobApplicationDate});}}catch(e){utag.DB(e)}},function(a,b){try{if(1){const matchStringOrArray=(input,value)=>{if(Array.isArray(input)){return input.includes(value);}
return input===value;};b.hotjarEventConfig={'verified_profile_displayed':{'eventName':'profile_displayed','currentPage':'profile','_custom_':document.querySelector("div[data-automation=certsy-verified-indicator-identity]")!==null},'unverified_profile_displayed':{'eventName':'profile_displayed','currentPage':'profile','_custom_':document.querySelector("div[data-automation=certsy-verified-indicator-identity]")===null},'apply_complete_displayed':{'_custom_':matchStringOrArray(b.eventName,'apply_complete_displayed')},'search_results_displayed':{'eventName':'search_results_displayed','currentPage':'search results'},'profile_displayed_sg_en':{'eventName':'profile_displayed','tiq_siteCountry':'sg','siteLanguage':'en'},'profile_displayed_nz':{'eventName':'profile_displayed','tiq_siteCountry':'nz'},'company_review_complete_displayed':{'eventName':'cr_write_a_review_complete_displayed','_custom_':b.tiq_siteCountry!=='hk'||b.tiq_siteCountry!=='th'},'company_review_complete_displayed_hk':{'eventName':'cr_write_a_review_complete_displayed','_custom_':b.tiq_siteCountry==='hk'||b.siteLanguage==='en'},'company_review_complete_displayed_hk_hk':{'eventName':'cr_write_a_review_complete_displayed','_custom_':b.tiq_siteCountry==='hk'||b.siteLanguage==='hk'},'company_review_complete_displayed_th':{'eventName':'cr_write_a_review_complete_displayed','_custom_':b.tiq_siteCountry==='th'||b.siteLanguage==='en'},'company_review_complete_displayed_th_th':{'eventName':'cr_write_a_review_complete_displayed','_custom_':b.tiq_siteCountry==='th'||b.siteLanguage==='th'},'job_details_displayed_non_linkout':{'eventName':'job_details_displayed','_custom_':String(b.jobIsLinkOut)!=='true'},'profile_verifications_widget_pressed_view_verifications':{'eventName':'profile_verifications_widget_pressed','_custom_':b.callToAction==="view_verifications"},'profile_verifications_widget_pressed_add_verification':{'eventName':'profile_verifications_widget_pressed','_custom_':b.callToAction==='add_verification_identity'}};}}catch(e){utag.DB(e)}},function(a,b,c,d,e,f,g){if(1){d=b['tiq_siteCountry'];if(typeof d=='undefined')return;c=[{'au':'162402'},{'nz':'335909'},{'id':'640499'},{'my':'390553'},{'ph':'640501'},{'sg':'640495'},{'hk':'337118'},{'th':'337118'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['hotjarId']=c[e][f];m=true};};if(m)break};if(!m)b['hotjarId']='';}}];u.isValidatedConfig=function(datalayer,config){for(let prop in config){if(prop==='_custom_'){if(config[prop]===false){return false;}}
else{if(datalayer[prop]!==config[prop]){return false;}}}
return true;};u.loader_cb=function(a,b){utag.DB("send:67:CALLBACK");if(u.initialized===true&&a=="view"){hj("stateChange",b["dom.pathname"]);}
u.initialized=true;if(!utag.ut.isEmptyObject(u.data.eventConfig)){for(let hjEvent in u.data.eventConfig){if(u.isValidatedConfig(b,u.data.eventConfig[hjEvent])){hj('event',hjEvent);}}}
utag.DB("send:67:CALLBACK:COMPLETE");};u.callBack=function(){var data={};while(data=u.queue.shift()){u.data=data.data;u.loader_cb(data.a,data.b);}};u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f;u.data={"hjid":"","hjsv":"","base_url":"//static.hotjar.com/c/hotjar-##utag_hjid##.js?sv=##utag_hjsv##","eventConfig":null};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
_hjSettings.hjid=u.data.hjid;_hjSettings.hjsv=u.data.hjsv;u.data.base_url=u.data.base_url.replace('##utag_hjid##',u.data.hjid);u.data.base_url=u.data.base_url.replace('##utag_hjsv##',u.data.hjsv);if(u.initialized){u.loader_cb(a,b);}else{u.queue.push({"data":u.data,"a":a,"b":b});if(!u.scriptrequested){u.scriptrequested=true;u.loader({"type":"script","src":u.data.base_url,"cb":u.callBack,"loc":"script","id":"utag_67","attrs":{}});}}}};utag.o[loader].loader.LOAD(id);}("67","seek.candidate-main"));}catch(error){utag.DB(error);}
