//tealium universal tag - utag.60 ut4.0.202508311047, Copyright 2025 Tealium.com Inc. All Rights Reserved.
window.analytics=window.analytics||[];analytics.SNIPPET_VERSION="5.2.0";try{(function(id,loader){var u={};u.id="60";utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id}if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={view:1,link:1};u.initialized=false;u.analytics=window.analytics;u.analytics.invoked=false;u.analytics.methods=["trackSubmit","trackClick","trackLink","trackForm","pageview","identify","reset","group","track","ready","alias","debug","page","screen","once","off","on","addSourceMiddleware","addIntegrationMiddleware","setAnonymousId","addDestinationMiddleware","register"];u.analytics.factory=function(e){return function(){if(u.analytics.initialized){return u.analytics[e].apply(u.analytics,arguments);}
var i=Array.prototype.slice.call(arguments);if(["track","screen","alias","group","page","identify"].indexOf(e)>-1){var c=document.querySelector("link[rel='canonical']");i.push({__t:"bpc",c:c&&c.getAttribute("href")||void 0,p:location.pathname,u:location.href,s:location.search,t:document.title,r:document.referrer});}
i.unshift(e);u.analytics.push(i);return u.analytics;}};u.map={};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:60:START");var c,d,e,f,i;u.data={"writeKey":"DvY7kWpoiUVpDNHDqjU0JWB8D0wslo4x","loadOptions":undefined,"base_url":"https://cdn.segment.com/analytics.js/v1/{writeKey}/analytics.min.js"};u.process_methods=function(methods){for(i=0;i<methods.length;i++){let key=methods[i];u.analytics[key]=u.analytics.factory(key);}}
for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
u.data.tag_id="utag_"+u.id;u.data.writeKey=u.data.writeKey||b.writeKey;u.data.loadOptions=u.data.loadOptions||b.loadOptions;u.data.base_url=u.data.base_url.replace("{writeKey}",u.data.writeKey);u.process_methods(u.analytics.methods);u.analytics._writeKey=u.data.writeKey;if(u.analytics.setAnonymousId&&b.tiq_deviceIdHashMd5){u.analytics.setAnonymousId(b.tiq_deviceIdHashMd5);}
u.loader_cb=function(){u.initialized=true;u.analytics.invoked=true;};if(u.initialized||document.getElementById(u.data.tag_id)){u.loader_cb();}else{u.loader({"type":"text/javascript","src":u.data.base_url,"cb":u.loader_cb,"loc":"script","id":u.data.tag_id});u.analytics._loadOptions=u.data.loadOptions;}
utag.DB("send:60:COMPLETE");}};utag.o[loader].loader.LOAD(id);})("60","seek.candidate-main");}catch(error){utag.DB(error);}
