//tealium universal tag - utag.197 ut4.0.202508311047, Copyright 2025 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};u.id="197";utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id}if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={view:1,link:1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){if(window.bundledHubbleTag&&!window.bundledHubbleTag._isQueueListenerSet){window.bundledHubbleTag.on('queue',(event)=>{if(event['name']==='tealium_iq_event'){window.seekTiq.hubbleEventId=event['id']}})
window.bundledHubbleTag._isQueueListenerSet=true;}}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['qp.platform']!='undefined'&&typeof b['qp.event_capture_session_id']!='undefined')){function getAppsPlatform(platform){switch(platform){case'ios_app':return'iOS';case'android_app':return'Android';default:return null;}}
b['tiq_ua_platform']=getAppsPlatform(b['qp.platform'])}}catch(e){utag.DB(e)}},function(a,b){try{if((typeof b['qp.event_capture_session_id']!='undefined'&&typeof b['qp.platform']!='undefined')){b['tiq_sessionId']=b['qp.event_capture_session_id']}}catch(e){utag.DB(e);}},function(a,b){try{if(b['tiq_isCareerAdvicePage']=='true'){if(b.pagePath&&typeof(b.pagePath)==='string'){b['tiq_currentPage']=`cca-${b.pagePath}`;}else{b['tiq_currentPage']=(b['currentPage']||b['pageTitle']);}
b['tiq_loginStatus']=(b.candidateId||b.loginId)?"true":"false";var deviceCategory=b['tiq_ua_deviceCategory'];if(deviceCategory&&deviceCategory=='desktop'){b['tiq_isMobile']='false';}else{b['tiq_isMobile']='true';}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){try{var eventType;if(b.eventName){var ev=b.eventName;if(Array.isArray(ev)){eventType=ev[0];}else if(typeof ev!=='string'){eventType="ERROR:EVENT_NAME_IN_WRONG_FORMAT"
b.amplitudeEventTypeError=JSON.stringify(ev);}else{eventType=ev;}
eventType=eventType.replace(/-/g,"_");eventType=eventType.replace(/\s/g,"_");eventType=eventType.replace("clicked","pressed");if(b["ut.event"]==="view"&&eventType!=="display_ad_viewed"){eventType=eventType.replace("viewed","displayed");}
if(eventType!=='career_advice_impression'){eventType=eventType.replace("impression","viewed");}}else{eventType='ERROR:PAGE_HAS_NO_EVENTNAME';}
b.amplitudeEventType=eventType.toLowerCase();}catch(e){b.amplitudeEventTypeError=e.toString();}}}catch(e){utag.DB(e)}},function(a,b){try{if(1){if(b['experiments']){var es=b['experiments'];es.forEach(function setExperiment(e){if(e.hasOwnProperty('num')){b['tiq_experiment'+e.num]=e.id+':'+e.variant;}});}
if(b['experimentsEligible']){var es=b['experimentsEligible'];es.forEach(function setExperiment(e){if(e.hasOwnProperty('num')){b['tiq_experimentEligible'+e.num]=e.id+':'+e.variant;}});}
if(b['experimentsParticipated']){var es=b['experimentsParticipated'];es.forEach(function setExperiment(e){if(e.hasOwnProperty('num')){b['tiq_experimentParticipated'+e.num]=e.id+':'+e.variant;}});}}}catch(e){utag.DB(e)}},function(a,b,c,d){try{if((typeof b['lmisType']!='undefined'&&typeof b['lmisContextType']!='undefined')){c=[b['lmisType'],b['lmisContextType']];b['lmisBanner']=c.join('|')}}catch(e){utag.DB(e);}},function(a,b){try{if(1){b.tiq_timestampEpochInMiliseconds=Date.now();b.tiq_eventIdentifier=b.tealium_visitor_id+'~'+b.tealium_session_id+'~'+b.tiq_timestampEpochInMiliseconds;}}catch(e){utag.DB(e)}},function(a,b){try{if(1){const em=b.errorMessage;const pd=b.parsedData;const as=b.alertShown;const ex=b.experiments;const jc=b.jobContacts;const en=b.eventName;const ls=b.learningSnippet;const cm=b.contactMatches;const ab=b.appBanner;const ci=b.contactInteraction;if(em&&Array.isArray(em)){if(em[0].hasOwnProperty('fieldName')===true){b.transformed_errorMessage=em.map((er)=>`${er.fieldName}:${er.errorType}`).join(" | ");}else{b.transformed_errorMessage=em.join(" | ");}}
if(pd&&Array.isArray(pd)){b.transformed_parsedData=pd.map((d)=>`${d.document}:${d.section}:${d.info}:${d.count}`).join(" | ");}
if(as&&Array.isArray(as)){b.transformed_alertShown=as.map((a)=>`${a.type.toLowerCase()}:${a.message}`).join("|");}
if(ex&&Array.isArray(ex)){b.transformed_experiments=ex.map((e)=>`${e.id.toLowerCase().replace(/ /gi,"-")}:${e.variant}`).join("|");}
if(jc){b.transformed_jobContacts=Array.isArray(jc)?jc.join().toLowerCase():jc;}
try{if(en){b.transformed_eventName=Array.isArray(en)?en.join():en;}
if(ls){if(ls.hasOwnProperty('skl-lmis')){b.transformed_learningSnippet=`${ls['skl-lmis-type']}:${ls['skl-lmis']}`;}else if(ls.hasOwnProperty('entity')){b.transformed_learningSnippet=`${ls.entity}:${ls.resultType}:${ls.variation}`;}else{b.transformed_learningSnippet='';}}
if(cm){b.transformed_contactMatches=Array.isArray(cm)?cm.join().toLowerCase():cm;}
if(ab&&ab.hasOwnProperty('type')){b.tiq_appBanner=ab.type+':'+ab.deviceType;}
if(ab&&ab.hasOwnProperty('device')){b.tiq_appBanner=ab.device+':'+ab.type;}
if(ci){if(ci.hasOwnProperty('interactionType')){b.transformed_jobContactAction=ci.interactionType}
if(ci.hasOwnProperty('contactType')){b.transformed_jobContactType=ci.contactType.toLowerCase()}}}catch(e){utag.DB(e);}}}catch(e){utag.DB(e)}},function(a,b,c,d,e,f,g){if(1){d=b['tiq_siteCountry'];if(typeof d=='undefined')return;c=[{'th':'THB'},{'hk':'HKD'},{'ph':'PHP'},{'id':'IDR'},{'my':'MYR'},{'sg':'SGD'},{'au':'AUD'},{'nz':'NZD'}];var m=false;for(e=0;e<c.length;e++){for(f in utag.loader.GV(c[e])){if(d==f){b['currencyCode']=c[e][f];m=true};};if(m)break};}},function(a,b){try{if(1){try{b['tiq_hubbleEventId']=window.seekTiq.hubbleEventId}catch(e){}}}catch(e){utag.DB(e);}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:197:START");var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
var isBundledHubbleTag=typeof window.bundledHubbleTag!=="undefined"&&typeof window.bundledHubbleTag.trackEvent==="function";const trimTealiumPayload=(event)=>{const copy=JSON.parse(JSON.stringify(event));const removalList=['cp.intercom','cp._hj','cp.panoramaId','cp.__rtbh','cp._uetsid','cp._uetvid','cp._fbp','cp._clsk','cp._clck','cp._pin','cp.da_past_event','cp.cto_bundle','cp._ga','cp._dd','cp.__stripe','cp._cc','cp._gcl','cp._legacy_','cp.main','cp.da_anz_candi_sid','cp.da_anz_hirer_sid','meta.'];for(const key in copy){removalList.forEach((prefix)=>{if(key.startsWith(prefix)){delete copy[key];}});}
return JSON.stringify(copy);};var trackTealiumEventWithHubble=(hubble,event)=>{if(event===null||typeof event!=="object"){return;}
const rawTealiumEvent=event.eventName||event.tealium_event||"";const tealiumEvent=typeof rawTealiumEvent==="string"?rawTealiumEvent:JSON.stringify(rawTealiumEvent);const trackingCorrelationId=typeof event.trackingCorrelationId==="string"?event.trackingCorrelationId:undefined;const payload=trimTealiumPayload(event);return hubble.trackEvent("tealium_iq_event",{tealiumEvent,payload},{trackingCorrelationId});};var parseExperimentDataTypes=(experiments)=>{if(experiments&&typeof experiments==='object'){const hubbleProperties={'id':{isRequired:false},'name':{isRequired:false},'participantStatus':{isRequired:false},'variant':{isRequired:true}}
for(const[key]of Object.entries(experiments)){if(experiments[key]){for(const[hProp]of Object.entries(hubbleProperties)){if(hubbleProperties[hProp].isRequired){experiments[key][hProp]=(experiments[key][hProp]!==null&&experiments[key][hProp]!==undefined)?String(experiments[key][hProp]):'undefined';}else{if(experiments[key][hProp]!==null&&experiments[key][hProp]!==undefined){experiments[key][hProp]=String(experiments[key][hProp]);}}}}}}
return experiments;}
var hubbleTiQ;var siteCountry=(b.tiq_siteCountry==='global')?'zz':String(b.tiq_siteCountry);var experience=b.tiq_experience?b.tiq_experience:'other';var hubbleExperiments=parseExperimentDataTypes(b.hubbleExperiments);var loginId=(b.loginId||b.userId||b.candidateId)?String(b.loginId||b.userId||b.candidateId):undefined;if(loginId&&(loginId.toLowerCase()==='null'||loginId.trim()==='')){loginId=undefined;}
function getTealiumEnvironment(b){const qpEnv=b['qp.env'];const qpPlatform=b['qp.platform'];if(qpEnv==='dev'&&['ios_app','android_app'].includes(qpPlatform)){return'dev';}else{return b.tealium_environment;}}
const env=getTealiumEnvironment(b);const isHirerPage=(b.tealium_profile==='hirer');const hubbleConfig={appName:"TiQ",appVersion:"0.0.1-20240212",brand:String(b.tiq_brand).toLowerCase(),country:String(siteCountry).toUpperCase(),experience:String(experience),loginId:loginId,experiments:hubbleExperiments,isProduction:env==='prod',installGlobalHubble:false,};if(isHirerPage){hubbleConfig.maximumBatchSize=1;}else{hubbleConfig.maximumBatchSize=3;}
const bundledHubbleObj=()=>new window.HubbleModule.Hubble(hubbleConfig);if(!isBundledHubbleTag){window.bundledHubbleTag=bundledHubbleObj();}
hubbleTiQ=window.bundledHubbleTag;if(hubbleTiQ===undefined){hubbleTiQ=bundledHubbleObj()}
hubbleTiQ.updateOptions({loginId:loginId,experiments:hubbleExperiments});trackTealiumEventWithHubble(hubbleTiQ,b);u.loader_cb=function(){u.initialized=true;};utag.DB("send:197:COMPLETE");}};utag.o[loader].loader.LOAD(id);})("197","seek.candidate-main");}catch(error){utag.DB(error);}
